services:
  - type: web
    name: sentispeech
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader vader_lexicon
    startCommand: gunicorn flask_app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data 