services:
  - type: web
    name: sentispeech
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 